# Generated by Django 3.2.4 on 2021-07-09 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allcourses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tophistorias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemid', models.JSONField()),
            ],
        ),
    ]
