# Generated by Django 3.2.4 on 2021-07-09 22:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('allcourses', '0002_tophistorias'),
    ]

    operations = [
        migrations.AddField(
            model_name='tophistorias',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
